### GET request to example server
### 1. Kategorier
GET http://localhost:8080/category
###
### adminroll
POST http://localhost:8080/category
Content-Type: application/json

{
  "name": "test",
  "symbol": null,
  "description": null
}
###
### 2.Platser
###
###(för anonyma användare).
GET http://localhost:8080/place
###
GET http://localhost:8080/category/1
###
### inloggade användaren
GET http://localhost:8080/places/user
###
### kräver inloggning).
POST http://localhost:8080/place
Content-Type: application/json

{
"name": "Sushi by Kyoto",
"categoryId": 2,
"userId": 104,
"published": true,
"lastChange": "2024-11-15T17:35:05Z",
"description": "A well-known sushi restaurants with amazing sushi",
"latitude": 59.3445102,
"longitude": 18.0398688,
"createdTime": "2024-11-15T17:35:05Z",
"deleted": false
}
###
### get all active places
GET http://localhost:8080/place/active
###
### get all inactive places
GET http://localhost:8080/place/inactive
###
###
DELETE http://localhost:8080/place/13
###
###
PUT http://localhost:8080/place/13
Content-Type: application/json

{
  "name": "Updated Place Name",
  "categoryId": 1,
  "userId": 101,
  "published": true,
  "lastChange": "2024-11-25T15:30:00Z",
  "description": "Updated description of the place.",
  "latitude": 59.3293,
  "longitude": 18.0686,
  "createdTime": "2024-11-23T19:10:05Z",
	"deleted": false
}
